# Project Proposal: Initial Data Information
Cassady Jackson and Baylie Schnieder

In [48]:
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import NoSuchElementException
from webdriver_manager.chrome import ChromeDriverManager
import time
import random

### Import Dataset 1
Using Pandas to import the CSV file from data.gov with information on Chronic Disease Indicators, which was created March 9th, 2024 and had the metadata updated on February 3rd, 2025.

Then displaying the dataset, and using .dtypes to show the data types in order to create the data dictionary for the project proposal.

In [51]:
chronic_data = pd.read_csv('U.S._Chronic_Disease_Indicators.csv')

In [52]:
display(chronic_data)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,TopicID,QuestionID,ResponseID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2019,2019,AR,Arkansas,BRFSS,Diabetes,Diabetes among adults,NaN,%,Crude Prevalence,...,DIA,DIA01,NaN,CRDPREV,SEX,SEXM,NaN,NaN,NaN,NaN
1,2019,2019,ID,Idaho,BRFSS,Diabetes,Diabetes among adults,NaN,%,Crude Prevalence,...,DIA,DIA01,NaN,CRDPREV,SEX,SEXM,NaN,NaN,NaN,NaN
2,2019,2019,IN,Indiana,YRBSS,Sleep,Short sleep duration among high school students,NaN,%,Crude Prevalence,...,SLEP,SLP02,NaN,CRDPREV,GRADE,GRD12,NaN,NaN,NaN,NaN
3,2019,2019,IA,Iowa,NVSS,Asthma,"Asthma mortality among all people, underlying ...",NaN,Number,Number,...,AST,AST01,NaN,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2019,2019,IA,Iowa,BRFSS,Asthma,Current asthma among adults,NaN,%,Crude Prevalence,...,AST,AST02,NaN,CRDPREV,AGE,AGE1844,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309210,2022,2022,VI,Virgin Islands,BRFSS,Tobacco,Quit attempts in the past year among adult cur...,NaN,%,Age-adjusted Prevalence,...,TOB,TOB06,NaN,AGEADJPREV,RACE,AIAN,NaN,NaN,NaN,NaN
309211,2022,2022,WV,West Virginia,BRFSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,NaN,%,Crude Prevalence,...,COPD,COPD01,NaN,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
309212,2022,2022,WI,Wisconsin,BRFSS,Immunization,Pneumococcal vaccination among adults aged 65 ...,NaN,%,Crude Prevalence,...,IMM,IMM04,NaN,CRDPREV,RACE,BLK,NaN,NaN,NaN,NaN
309213,2022,2022,VT,Vermont,BRFSS,Social Determinants of Health,Lack of health insurance among adults aged 18-...,NaN,%,Crude Prevalence,...,SDOH,SDH09,NaN,CRDPREV,RACE,HAPI,NaN,NaN,NaN,NaN
309214,2022,2022,WA,Washington,BRFSS,Alcohol,Binge drinking prevalence among adults,NaN,%,Age-adjusted Prevalence,...,ALC,ALC06,NaN,AGEADJPREV,SEX,SEXM,NaN,NaN,NaN,NaN

In [55]:
print(chronic_data.dtypes)

YearStart                      int64
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
DataSource                    object
Topic                         object
Question                      object
Response                     float64
DataValueUnit                 object
DataValueType                 object
DataValue                    float64
DataValueAlt                 float64
DataValueFootnoteSymbol       object
DataValueFootnote             object
LowConfidenceLimit           float64
HighConfidenceLimit          float64
StratificationCategory1       object
Stratification1               object
StratificationCategory2      float64
Stratification2              float64
StratificationCategory3      float64
Stratification3              float64
Geolocation                   object
LocationID                     int64
TopicID                       object
QuestionID                    object
ResponseID                   float64
DataValueTypeID               object
StratificationCategoryID1     object
StratificationID1             object
StratificationCategoryID2    float64
StratificationID2            float64
StratificationCategoryID3    float64
StratificationID3            float64
dtype: object

In [57]:
print("Missing Data Summary: \n", "-" *50)
print(chronic_data.isna().sum())
print('\n')
print(f'Total missing data: {chronic_data.isna().sum().sum()}')

Missing Data Summary:
 --------------------------------------------------
YearStart                         0
YearEnd                           0
LocationAbbr                      0
LocationDesc                      0
DataSource                        0
Topic                             0
Question                          0
Response                     309215
DataValueUnit                     0
DataValueType                     0
DataValue                    100019
DataValueAlt                 100019
DataValueFootnoteSymbol      207499
DataValueFootnote            207499
LowConfidenceLimit           120330
HighConfidenceLimit          120325
StratificationCategory1           0
Stratification1                   0
StratificationCategory2      309215
Stratification2              309215
StratificationCategory3      309215
Stratification3              309215
Geolocation                    5763
LocationID                        0
TopicID                           0
QuestionID                        0
ResponseID                   309215
DataValueTypeID                   0
StratificationCategoryID1         0
StratificationID1                 0
StratificationCategoryID2    309215
StratificationID2            309215
StratificationCategoryID3    309215
StratificationID3            309215
dtype: int64


Total missing data: 3953604

Dropping the missing values in DataValue, and confidence limits so that they can be used for analysis without error.

In [60]:
clean_chronic_data = chronic_data.dropna(subset = ['DataValue','LowConfidenceLimit','HighConfidenceLimit'])

In [62]:
print("Missing Data Summary: \n", "-" *50)
print(clean_chronic_data.isna().sum())
print('\n')
print(f'Total missing data: {clean_chronic_data.isna().sum().sum()}')

Missing Data Summary:
 --------------------------------------------------
YearStart                         0
YearEnd                           0
LocationAbbr                      0
LocationDesc                      0
DataSource                        0
Topic                             0
Question                          0
Response                     188885
DataValueUnit                     0
DataValueType                     0
DataValue                         0
DataValueAlt                      0
DataValueFootnoteSymbol      187361
DataValueFootnote            187361
LowConfidenceLimit                0
HighConfidenceLimit               0
StratificationCategory1           0
Stratification1                   0
StratificationCategory2      188885
Stratification2              188885
StratificationCategory3      188885
Stratification3              188885
Geolocation                    4537
LocationID                        0
TopicID                           0
QuestionID                        0
ResponseID                   188885
DataValueTypeID                   0
StratificationCategoryID1         0
StratificationID1                 0
StratificationCategoryID2    188885
StratificationID2            188885
StratificationCategoryID3    188885
StratificationID3            188885
dtype: int64


Total missing data: 2268109

Dropping columns with exclusively missing values.

In [65]:
clean_chronic_data = clean_chronic_data.dropna(axis=1)
display(clean_chronic_data)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,...,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,2019,2019,AR,Arkansas,BRFSS,Diabetes,Diabetes among adults,%,Crude Prevalence,13.6,...,12.1,15.4,Sex,Male,5,DIA,DIA01,CRDPREV,SEX,SEXM
1,2019,2019,ID,Idaho,BRFSS,Diabetes,Diabetes among adults,%,Crude Prevalence,10.6,...,9.1,12.2,Sex,Male,16,DIA,DIA01,CRDPREV,SEX,SEXM
4,2019,2019,IA,Iowa,BRFSS,Asthma,Current asthma among adults,%,Crude Prevalence,10.3,...,9.1,11.7,Age,Age 18-44,19,AST,AST02,CRDPREV,AGE,AGE1844
6,2019,2019,IA,Iowa,BRFSS,Health Status,Recent activity limitation among adults,Number,Crude Mean,2.3,...,2.1,2.5,Sex,Female,19,HEA,HEA04,CRDMEAN,SEX,SEXF
7,2019,2019,IA,Iowa,BRFSS,Mental Health,Depression among adults,%,Crude Prevalence,31.0,...,20.6,43.7,Race/Ethnicity,"Multiracial, non-Hispanic",19,MEN,MEN02,CRDPREV,RACE,MRC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309208,2022,2022,VT,Vermont,BRFSS,Sleep,Short sleep duration among adults,%,Crude Prevalence,26.5,...,16.8,39.3,Race/Ethnicity,"Asian, non-Hispanic",50,SLEP,SLP03,CRDPREV,RACE,ASN
309209,2022,2022,VI,Virgin Islands,BRFSS,Immunization,Influenza vaccination among adults,%,Crude Prevalence,34.2,...,24.2,45.8,Age,Age >=65,78,IMM,IMM01,CRDPREV,AGE,AGE65P
309211,2022,2022,WV,West Virginia,BRFSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,%,Crude Prevalence,14.0,...,12.8,15.2,Overall,Overall,54,COPD,COPD01,CRDPREV,OVERALL,OVR
309212,2022,2022,WI,Wisconsin,BRFSS,Immunization,Pneumococcal vaccination among adults aged 65 ...,%,Crude Prevalence,64.2,...,52.2,74.6,Race/Ethnicity,"Black, non-Hispanic",55,IMM,IMM04,CRDPREV,RACE,BLK
309214,2022,2022,WA,Washington,BRFSS,Alcohol,Binge drinking prevalence among adults,%,Age-adjusted Prevalence,19.2,...,18.3,20.2,Sex,Male,53,ALC,ALC06,AGEADJPREV,SEX,SEXM

Printing the new columns after the missing values were dropped to create the data dictionary

In [68]:
print(clean_chronic_data.dtypes)

YearStart                      int64
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
DataSource                    object
Topic                         object
Question                      object
DataValueUnit                 object
DataValueType                 object
DataValue                    float64
DataValueAlt                 float64
LowConfidenceLimit           float64
HighConfidenceLimit          float64
StratificationCategory1       object
Stratification1               object
LocationID                     int64
TopicID                       object
QuestionID                    object
DataValueTypeID               object
StratificationCategoryID1     object
StratificationID1             object
dtype: object

In [81]:
clean_chronic_data.to_csv('Cleaned_Chronic_Data.csv', header=True, index=False, encoding="utf-8")

### Scraping for the Second Data Set

In [13]:
browser = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
url = "https://worldpopulationreview.com/state-rankings/public-school-rankings-by-state"
browser.get(url)
time.sleep(random.uniform(1,3))

In [14]:
table = browser.find_element(By.TAG_NAME, "table")
rows = table.find_elements(By.TAG_NAME, "tr")

data = []
for row in rows:
    cols = row.find_elements(By.TAG_NAME, "td")
    cols = [col.text.strip() for col in cols]
    if cols:
        data.append(cols)

public_ed_data = pd.DataFrame(data)
display(public_ed_data)

   0                     1   2   3   4   5   6
0            Massachusetts   1   1   2  38  37
1                 New York   2  31   1  12   5
2               New Jersey   3  11   5  13   2
3               Washington   4  16  11   4  24
4             Pennsylvania   5   3   8  44  14
5                  Vermont   6   5   6  50  26
6                Minnesota   7   8  19  27  19
7              Connecticut   8  18   3  24   4
8                 Virginia   9  19  21  11  17
9                Wisconsin  10  10  25  19  20
10                 Wyoming  11   6  17  14  36
11                Maryland  12  28  10  18  27
12                   Maine  13  14  15  46  13
13                Nebraska  14  15  27  23  15
14            Rhode Island  15  32   7  47   8
15           New Hampshire  16   2  12  51  40
16                Illinois  17  22   9   6  10
17            South Dakota  18   9  43  33   1
18            North Dakota  19   7  29  35  33
19                 Montana  20  13  37  49  11
20    District of Columbia  21  34   4  42  50
21                    Iowa  22  12  36  26  42
22                Michigan  23  26  26  41   9
23                Missouri  24  27  30  29  21
24                Kentucky  25  39  24  15  29
25                    Ohio  26  25  23  48  25
26                  Alaska  27  33  16   5  48
27               Tennessee  28  30  40   9  28
28                  Kansas  29  20  28  34  38
29                 Georgia  30  36  22   3  12
30                  Oregon  31  29  20  37  44
31              California  32  41  18   2  39
32                  Hawaii  33  24  14  20  34
33          North Carolina  34  35  42   7  32
34                Colorado  35  17  33  28  22
35                Delaware  36  38  13  17  30
36                    Utah  37   4  51  40  35
37          South Carolina  38  43  32  10  49
38             Mississippi  39  46  38  32  16
39                   Texas  40  48  44  21   7
40                 Florida  41  37  47   1   6
41               Louisiana  42  45  46  22  23
42                 Indiana  43  23  41  25  31
43                  Nevada  44  44  45  16  46
44                Arkansas  45  42  35  30  43
45           West Virginia  46  50  34  31  41
46                   Idaho  47  21  48  39   3
47                Oklahoma  48  49  49  36  18
48              New Mexico  49  51  31   8  51
49                 Alabama  50  47  39  45  47
50                 Arizona  51  40  50  43  45

In [15]:
browser.quit()

In [16]:
public_ed_data.columns = ['Count','State','Overall Public School Rank 2024', 'K-12 Performance 2024', 'School Funding and Resources 2024', 'Higher Ed Quality 2024', 'School Safety Rank 2024']

In [17]:
public_ed_data = public_ed_data.drop(columns='Count')

In [18]:
display(public_ed_data)

,State,Overall Public School Rank 2024,K-12 Performance 2024,School Funding and Resources 2024,Higher Ed Quality 2024,School Safety Rank 2024
0,Massachusetts,1,1,2,38,37
1,New York,2,31,1,12,5
2,New Jersey,3,11,5,13,2
3,Washington,4,16,11,4,24
4,Pennsylvania,5,3,8,44,14
5,Vermont,6,5,6,50,26
6,Minnesota,7,8,19,27,19
7,Connecticut,8,18,3,24,4
8,Virginia,9,19,21,11,17
9,Wisconsin,10,10,25,19,20
10,Wyoming,11,6,17,14,36
11,Maryland,12,28,10,18,27
12,Maine,13,14,15,46,13
13,Nebraska,14,15,27,23,15
14,Rhode Island,15,32,7,47,8
15,New Hampshire,16,2,12,51,40
16,Illinois,17,22,9,6,10
17,South Dakota,18,9,43,33,1
18,North Dakota,19,7,29,35,33
19,Montana,20,13,37,49,11
20,District of Columbia,21,34,4,42,50
21,Iowa,22,12,36,26,42
22,Michigan,23,26,26,41,9
23,Missouri,24,27,30,29,21
24,Kentucky,25,39,24,15,29
25,Ohio,26,25,23,48,25
26,Alaska,27,33,16,5,48
27,Tennessee,28,30,40,9,28
28,Kansas,29,20,28,34,38
29,Georgia,30,36,22,3,12
30,Oregon,31,29,20,37,44
31,California,32,41,18,2,39
32,Hawaii,33,24,14,20,34
33,North Carolina,34,35,42,7,32
34,Colorado,35,17,33,28,22
35,Delaware,36,38,13,17,30
36,Utah,37,4,51,40,35
37,South Carolina,38,43,32,10,49
38,Mississippi,39,46,38,32,16
39,Texas,40,48,44,21,7
40,Florida,41,37,47,1,6
41,Louisiana,42,45,46,22,23
42,Indiana,43,23,41,25,31
43,Nevada,44,44,45,16,46
44,Arkansas,45,42,35,30,43
45,West Virginia,46,50,34,31,41
46,Idaho,47,21,48,39,3
47,Oklahoma,48,49,49,36,18
48,New Mexico,49,51,31,8,51
49,Alabama,50,47,39,45,47
50,Arizona,51,40,50,43,45

Printing the datatypes of the scraped dataset to add to the data dictionary

In [20]:
print(public_ed_data.dtypes)

State                                object
Overall Public School Rank 2024      object
K-12 Performance 2024                object
School Funding and Resources 2024    object
Higher Ed Quality 2024               object
School Safety Rank 2024              object
dtype: object

In [83]:
public_ed_data.to_csv('State_Ed_Rankings.csv', header=True, index=False, encoding="utf-8")

# Integrating the Datasets

In order to integrate the datasets we will need to ensure both dataframes include columns that are similar enough to combine. Based on the data in each set, the easiest method would be to combine the data based on the 'State' column in the scraped dataset, and the 'LocationDesc' column in the other dataset.
- The first thing that will need to be done to combine these two datasets is the renaming of the 'LocationDesc' column to match the 'State' column.
- They will then need to be combined, preserving the data in both sets using merge.

In [75]:
clean_chronic_data = clean_chronic_data.rename(columns={'LocationDesc' : 'State'})

In [77]:
data_inner = pd.merge(clean_chronic_data, public_ed_data, on='State', how='inner')
display(data_inner)

,YearStart,YearEnd,LocationAbbr,State,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,...,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,Overall Public School Rank 2024,K-12 Performance 2024,School Funding and Resources 2024,Higher Ed Quality 2024,School Safety Rank 2024
0,2019,2019,AR,Arkansas,BRFSS,Diabetes,Diabetes among adults,%,Crude Prevalence,13.6,...,DIA,DIA01,CRDPREV,SEX,SEXM,45,42,35,30,43
1,2019,2019,ID,Idaho,BRFSS,Diabetes,Diabetes among adults,%,Crude Prevalence,10.6,...,DIA,DIA01,CRDPREV,SEX,SEXM,47,21,48,39,3
2,2019,2019,IA,Iowa,BRFSS,Asthma,Current asthma among adults,%,Crude Prevalence,10.3,...,AST,AST02,CRDPREV,AGE,AGE1844,22,12,36,26,42
3,2019,2019,IA,Iowa,BRFSS,Health Status,Recent activity limitation among adults,Number,Crude Mean,2.3,...,HEA,HEA04,CRDMEAN,SEX,SEXF,22,12,36,26,42
4,2019,2019,IA,Iowa,BRFSS,Mental Health,Depression among adults,%,Crude Prevalence,31.0,...,MEN,MEN02,CRDPREV,RACE,MRC,22,12,36,26,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179610,2022,2022,WV,West Virginia,BRFSS,Mental Health,Frequent mental distress among adults,%,Age-adjusted Prevalence,26.0,...,MEN,MEN05,AGEADJPREV,SEX,SEXF,46,50,34,31,41
179611,2022,2022,VT,Vermont,BRFSS,Sleep,Short sleep duration among adults,%,Crude Prevalence,26.5,...,SLEP,SLP03,CRDPREV,RACE,ASN,6,5,6,50,26
179612,2022,2022,WV,West Virginia,BRFSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,%,Crude Prevalence,14.0,...,COPD,COPD01,CRDPREV,OVERALL,OVR,46,50,34,31,41
179613,2022,2022,WI,Wisconsin,BRFSS,Immunization,Pneumococcal vaccination among adults aged 65 ...,%,Crude Prevalence,64.2,...,IMM,IMM04,CRDPREV,RACE,BLK,10,10,25,19,20
179614,2022,2022,WA,Washington,BRFSS,Alcohol,Binge drinking prevalence among adults,%,Age-adjusted Prevalence,19.2,...,ALC,ALC06,AGEADJPREV,SEX,SEXM,4,16,11,4,24

In [79]:
data_inner.to_csv('State_Unique_Data.csv', header=True, index=False, encoding="utf-8")