# Project Proposal: Initial Data Information
Cassady Jackson and Baylie Schnieder

In [36]:
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import NoSuchElementException
from webdriver_manager.chrome import ChromeDriverManager
import time
import random

### Import Dataset 1
Using Pandas to import the CSV file from data.gov with information on Chronic Disease Indicators, which was created March 9th, 2024 and had the metadata updated on February 3rd, 2025.

Then displaying the dataset, and using .dtypes to show the data types in order to create the data dictionary for the project proposal.

In [37]:
chronic_data = pd.read_csv('U.S._Chronic_Disease_Indicators.csv')

In [38]:
display(chronic_data)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,TopicID,QuestionID,ResponseID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2020,2020,US,United States,BRFSS,Health Status,Recent activity limitation among adults,NaN,Number,Age-adjusted Mean,...,HEA,HEA04,NaN,AGEADJMEAN,SEX,SEXF,NaN,NaN,NaN,NaN
1,2015,2019,AR,Arkansas,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,Number,Number,...,CAN,CAN07,NaN,NMBR,SEX,SEXM,NaN,NaN,NaN,NaN
2,2015,2019,CA,California,US Cancer DVT,Cancer,"Cervical cancer mortality among all females, u...",NaN,Number,Number,...,CAN,CAN03,NaN,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2015,2019,CO,Colorado,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,Number,Number,...,CAN,CAN07,NaN,NMBR,RACE,HIS,NaN,NaN,NaN,NaN
4,2015,2019,GA,Georgia,US Cancer DVT,Cancer,"Prostate cancer mortality among all males, und...",NaN,Number,Number,...,CAN,CAN05,NaN,NMBR,RACE,WHT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309210,2022,2022,VI,Virgin Islands,BRFSS,Tobacco,Quit attempts in the past year among adult cur...,NaN,%,Age-adjusted Prevalence,...,TOB,TOB06,NaN,AGEADJPREV,RACE,AIAN,NaN,NaN,NaN,NaN
309211,2022,2022,WV,West Virginia,BRFSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,NaN,%,Crude Prevalence,...,COPD,COPD01,NaN,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
309212,2022,2022,WI,Wisconsin,BRFSS,Immunization,Pneumococcal vaccination among adults aged 65 ...,NaN,%,Crude Prevalence,...,IMM,IMM04,NaN,CRDPREV,RACE,BLK,NaN,NaN,NaN,NaN
309213,2022,2022,VT,Vermont,BRFSS,Social Determinants of Health,Lack of health insurance among adults aged 18-...,NaN,%,Crude Prevalence,...,SDOH,SDH09,NaN,CRDPREV,RACE,HAPI,NaN,NaN,NaN,NaN
309214,2022,2022,WA,Washington,BRFSS,Alcohol,Binge drinking prevalence among adults,NaN,%,Age-adjusted Prevalence,...,ALC,ALC06,NaN,AGEADJPREV,SEX,SEXM,NaN,NaN,NaN,NaN

In [39]:
print(chronic_data.dtypes)

YearStart                      int64
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
DataSource                    object
Topic                         object
Question                      object
Response                     float64
DataValueUnit                 object
DataValueType                 object
DataValue                    float64
DataValueAlt                 float64
DataValueFootnoteSymbol       object
DataValueFootnote             object
LowConfidenceLimit           float64
HighConfidenceLimit          float64
StratificationCategory1       object
Stratification1               object
StratificationCategory2      float64
Stratification2              float64
StratificationCategory3      float64
Stratification3              float64
Geolocation                   object
LocationID                     int64
TopicID                       object
QuestionID                    object
ResponseID                   float64
DataValueTypeID               object
StratificationCategoryID1     object
StratificationID1             object
StratificationCategoryID2    float64
StratificationID2            float64
StratificationCategoryID3    float64
StratificationID3            float64
dtype: object

In [40]:
print("Missing Data Summary: \n", "-" *50)
print(chronic_data.isna().sum())
print('\n')
print(f'Total missing data: {chronic_data.isna().sum().sum()}')

Missing Data Summary:
 --------------------------------------------------
YearStart                         0
YearEnd                           0
LocationAbbr                      0
LocationDesc                      0
DataSource                        0
Topic                             0
Question                          0
Response                     309215
DataValueUnit                     0
DataValueType                     0
DataValue                    100019
DataValueAlt                 100019
DataValueFootnoteSymbol      207499
DataValueFootnote            207499
LowConfidenceLimit           120330
HighConfidenceLimit          120325
StratificationCategory1           0
Stratification1                   0
StratificationCategory2      309215
Stratification2              309215
StratificationCategory3      309215
Stratification3              309215
Geolocation                    5763
LocationID                        0
TopicID                           0
QuestionID                        0
ResponseID                   309215
DataValueTypeID                   0
StratificationCategoryID1         0
StratificationID1                 0
StratificationCategoryID2    309215
StratificationID2            309215
StratificationCategoryID3    309215
StratificationID3            309215
dtype: int64


Total missing data: 3953604

Dropping the missing values in DataValue, and confidence limits so that they can be used for analysis without error.

In [41]:
clean_chronic_data = chronic_data.dropna(subset = ['DataValue','LowConfidenceLimit','HighConfidenceLimit'])

In [42]:
print("Missing Data Summary: \n", "-" *50)
print(clean_chronic_data.isna().sum())
print('\n')
print(f'Total missing data: {clean_chronic_data.isna().sum().sum()}')

Missing Data Summary:
 --------------------------------------------------
YearStart                         0
YearEnd                           0
LocationAbbr                      0
LocationDesc                      0
DataSource                        0
Topic                             0
Question                          0
Response                     188885
DataValueUnit                     0
DataValueType                     0
DataValue                         0
DataValueAlt                      0
DataValueFootnoteSymbol      187361
DataValueFootnote            187361
LowConfidenceLimit                0
HighConfidenceLimit               0
StratificationCategory1           0
Stratification1                   0
StratificationCategory2      188885
Stratification2              188885
StratificationCategory3      188885
Stratification3              188885
Geolocation                    4537
LocationID                        0
TopicID                           0
QuestionID                        0
ResponseID                   188885
DataValueTypeID                   0
StratificationCategoryID1         0
StratificationID1                 0
StratificationCategoryID2    188885
StratificationID2            188885
StratificationCategoryID3    188885
StratificationID3            188885
dtype: int64


Total missing data: 2268109

Dropping columns with exclusively missing values.

In [43]:
clean_chronic_data = clean_chronic_data.dropna(axis=1)
display(clean_chronic_data)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,...,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,2020,2020,US,United States,BRFSS,Health Status,Recent activity limitation among adults,Number,Age-adjusted Mean,2.9,...,2.8,2.9,Sex,Female,59,HEA,HEA04,AGEADJMEAN,SEX,SEXF
10,2015,2019,SD,South Dakota,US Cancer DVT,Cancer,"Prostate cancer mortality among all males, und...","per 100,000",Crude Rate,20.2,...,18.4,22.2,Overall,Overall,46,CAN,CAN05,CRDRATE,OVERALL,OVR
11,2015,2019,TX,Texas,US Cancer DVT,Cancer,"Cervical cancer mortality among all females, u...","per 100,000",Crude Rate,2.9,...,2.8,3.0,Sex,Female,48,CAN,CAN03,CRDRATE,SEX,SEXF
13,2015,2019,VT,Vermont,US Cancer DVT,Cancer,"Prostate cancer mortality among all males, und...","per 100,000",Crude Rate,23.0,...,20.7,25.5,Overall,Overall,50,CAN,CAN05,CRDRATE,OVERALL,OVR
14,2015,2019,WV,West Virginia,US Cancer DVT,Cancer,"Breast cancer mortality among all females, und...","per 100,000",Crude Rate,31.6,...,30.0,33.2,Sex,Female,54,CAN,CAN02,CRDRATE,SEX,SEXF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309208,2022,2022,VT,Vermont,BRFSS,Sleep,Short sleep duration among adults,%,Crude Prevalence,26.5,...,16.8,39.3,Race/Ethnicity,"Asian, non-Hispanic",50,SLEP,SLP03,CRDPREV,RACE,ASN
309209,2022,2022,VI,Virgin Islands,BRFSS,Immunization,Influenza vaccination among adults,%,Crude Prevalence,34.2,...,24.2,45.8,Age,Age >=65,78,IMM,IMM01,CRDPREV,AGE,AGE65P
309211,2022,2022,WV,West Virginia,BRFSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,%,Crude Prevalence,14.0,...,12.8,15.2,Overall,Overall,54,COPD,COPD01,CRDPREV,OVERALL,OVR
309212,2022,2022,WI,Wisconsin,BRFSS,Immunization,Pneumococcal vaccination among adults aged 65 ...,%,Crude Prevalence,64.2,...,52.2,74.6,Race/Ethnicity,"Black, non-Hispanic",55,IMM,IMM04,CRDPREV,RACE,BLK
309214,2022,2022,WA,Washington,BRFSS,Alcohol,Binge drinking prevalence among adults,%,Age-adjusted Prevalence,19.2,...,18.3,20.2,Sex,Male,53,ALC,ALC06,AGEADJPREV,SEX,SEXM

Printing the new columns after the missing values were dropped to create the data dictionary

In [44]:
print(clean_chronic_data.dtypes)

YearStart                      int64
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
DataSource                    object
Topic                         object
Question                      object
DataValueUnit                 object
DataValueType                 object
DataValue                    float64
DataValueAlt                 float64
LowConfidenceLimit           float64
HighConfidenceLimit          float64
StratificationCategory1       object
Stratification1               object
LocationID                     int64
TopicID                       object
QuestionID                    object
DataValueTypeID               object
StratificationCategoryID1     object
StratificationID1             object
dtype: object

Dropping the columns that contain years that we do not have education ranking data for. This means keeping only the data from 2022.

In [45]:
clean_chronic_data = clean_chronic_data.drop(clean_chronic_data[clean_chronic_data['YearEnd'] != 2022.].index)

In [46]:
clean_chronic_data = clean_chronic_data.drop(columns='YearStart')

In [47]:
clean_chronic_data.to_csv('Cleaned_Chronic_Data.csv', header=True, index=False, encoding="utf-8")

### Scraping for the Second Data Set

In [49]:
browser = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
url = "https://web.archive.org/web/20220306220650/https://worldpopulationreview.com/state-rankings/public-school-rankings-by-state"
browser.get(url)
time.sleep(random.uniform(1,3))

In [50]:
table = browser.find_element(By.TAG_NAME, "table")
rows = table.find_elements(By.TAG_NAME, "tr")

data = []
for row in rows:
    cols = row.find_elements(By.TAG_NAME, "td")
    cols = [col.text.strip() for col in cols]
    if cols:
        data.append(cols)

public_ed_data = pd.DataFrame(data)
display(public_ed_data)

                 0   1   2   3
0    Massachusetts   1   1   1
1      Connecticut   2   2  19
2       New Jersey   3   3  15
3         Virginia   4   4   3
4          Vermont   5   8   4
5    New Hampshire   6   7   6
6        Minnesota   7   6  22
7        Wisconsin   8   5  24
8         Delaware   9  15   2
9         Maryland  10  11   9
10        Nebraska  11  12   8
11        New York  12  16  10
12        Illinois  13  10  28
13    North Dakota  14   9  34
14         Indiana  15  23  12
15        Kentucky  16  14  33
16        Colorado  17  17  27
17            Utah  18  20  18
18         Wyoming  19  18  29
19           Maine  20  24  14
20      Washington  21  26   5
21         Florida  22  19  35
22            Iowa  23  25  16
23    Pennsylvania  24  22  30
24    South Dakota  25  13  46
25         Montana  26  21  42
26    Rhode Island  27  29  11
27           Texas  28  30  13
28          Kansas  29  27  25
29  North Carolina  30  28  21
30          Hawaii  31  36  26
31            Ohio  32  33  39
32        Michigan  33  34  38
33         Georgia  34  37  36
34       Tennessee  35  31  45
35        Missouri  36  32  48
36      California  37  38  32
37           Idaho  38  35  50
38   West Virginia  39  45   7
39          Oregon  40  40  37
40        Arkansas  42  39  51
41  South Carolina  43  42  41
42         Alabama  44  46  17
43          Nevada  45  44  40
44     Mississippi  46  43  43
45        Oklahoma  47  48  20
46          Alaska  48  50  34
47         Arizona  49  50  31
48       Louisiana  50  49  47
49      New Mexico  51  51  49

In [51]:
browser.quit()

In [52]:
public_ed_data.columns = ['State','Overall Public School Rank 2022', 'Higher Ed Quality 2022', 'School Safety Rank 2022']

In [53]:
display(public_ed_data)

,State,Overall Public School Rank 2022,Higher Ed Quality 2022,School Safety Rank 2022
0,Massachusetts,1,1,1
1,Connecticut,2,2,19
2,New Jersey,3,3,15
3,Virginia,4,4,3
4,Vermont,5,8,4
5,New Hampshire,6,7,6
6,Minnesota,7,6,22
7,Wisconsin,8,5,24
8,Delaware,9,15,2
9,Maryland,10,11,9
10,Nebraska,11,12,8
11,New York,12,16,10
12,Illinois,13,10,28
13,North Dakota,14,9,34
14,Indiana,15,23,12
15,Kentucky,16,14,33
16,Colorado,17,17,27
17,Utah,18,20,18
18,Wyoming,19,18,29
19,Maine,20,24,14
20,Washington,21,26,5
21,Florida,22,19,35
22,Iowa,23,25,16
23,Pennsylvania,24,22,30
24,South Dakota,25,13,46
25,Montana,26,21,42
26,Rhode Island,27,29,11
27,Texas,28,30,13
28,Kansas,29,27,25
29,North Carolina,30,28,21
30,Hawaii,31,36,26
31,Ohio,32,33,39
32,Michigan,33,34,38
33,Georgia,34,37,36
34,Tennessee,35,31,45
35,Missouri,36,32,48
36,California,37,38,32
37,Idaho,38,35,50
38,West Virginia,39,45,7
39,Oregon,40,40,37
40,Arkansas,42,39,51
41,South Carolina,43,42,41
42,Alabama,44,46,17
43,Nevada,45,44,40
44,Mississippi,46,43,43
45,Oklahoma,47,48,20
46,Alaska,48,50,34
47,Arizona,49,50,31
48,Louisiana,50,49,47
49,New Mexico,51,51,49

Printing the datatypes of the scraped dataset to add to the data dictionary

In [54]:
print(public_ed_data.dtypes)

State                              object
Overall Public School Rank 2022    object
Higher Ed Quality 2022             object
School Safety Rank 2022            object
dtype: object

In [55]:
public_ed_data.to_csv('State_Ed_Rankings.csv', header=True, index=False, encoding="utf-8")

# Integrating the Datasets

In order to integrate the datasets we will need to ensure both dataframes include columns that are similar enough to combine. Based on the data in each set, the easiest method would be to combine the data based on the 'State' column in the scraped dataset, and the 'LocationDesc' column in the other dataset.
- The first thing that will need to be done to combine these two datasets is the renaming of the 'LocationDesc' column to match the 'State' column.
- They will then need to be combined, preserving the data in both sets using merge.

In [56]:
clean_chronic_data = clean_chronic_data.rename(columns={'LocationDesc' : 'State'})

In [57]:
data_inner = pd.merge(clean_chronic_data, public_ed_data, on='State', how='inner')
display(data_inner)

,YearEnd,LocationAbbr,State,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,DataValueAlt,...,Stratification1,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,Overall Public School Rank 2022,Higher Ed Quality 2022,School Safety Rank 2022
0,2022,OH,Ohio,BRFSS,Disability,Adults with any disability,%,Age-adjusted Prevalence,42.8,42.8,...,"Multiracial, non-Hispanic",39,DIS,DIS01,AGEADJPREV,RACE,MRC,32,33,39
1,2022,WY,Wyoming,BRFSS,Cognitive Health and Caregiving,Provided care for someone with dementia or oth...,%,Crude Prevalence,21.5,21.5,...,Age 45-64,56,CHC,CHC03,CRDPREV,AGE,AGE4564,19,18,29
2,2022,AL,Alabama,BRFSS,Asthma,Current asthma among adults,%,Age-adjusted Prevalence,7.4,7.4,...,Male,1,AST,AST02,AGEADJPREV,SEX,SEXM,44,46,17
3,2022,AL,Alabama,BRFSS,Mental Health,Frequent mental distress among adults,%,Crude Prevalence,15.0,15.0,...,Male,1,MEN,MEN05,CRDPREV,SEX,SEXM,44,46,17
4,2022,AL,Alabama,BRFSS,Oral Health,No teeth lost among adults aged 18-64 years,%,Crude Prevalence,42.7,42.7,...,Age 45-64,1,ORH,ORH01,CRDPREV,AGE,AGE4564,44,46,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29908,2022,WV,West Virginia,BRFSS,Mental Health,Frequent mental distress among adults,%,Age-adjusted Prevalence,26.0,26.0,...,Female,54,MEN,MEN05,AGEADJPREV,SEX,SEXF,39,45,7
29909,2022,VT,Vermont,BRFSS,Sleep,Short sleep duration among adults,%,Crude Prevalence,26.5,26.5,...,"Asian, non-Hispanic",50,SLEP,SLP03,CRDPREV,RACE,ASN,5,8,4
29910,2022,WV,West Virginia,BRFSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,%,Crude Prevalence,14.0,14.0,...,Overall,54,COPD,COPD01,CRDPREV,OVERALL,OVR,39,45,7
29911,2022,WI,Wisconsin,BRFSS,Immunization,Pneumococcal vaccination among adults aged 65 ...,%,Crude Prevalence,64.2,64.2,...,"Black, non-Hispanic",55,IMM,IMM04,CRDPREV,RACE,BLK,8,5,24
29912,2022,WA,Washington,BRFSS,Alcohol,Binge drinking prevalence among adults,%,Age-adjusted Prevalence,19.2,19.2,...,Male,53,ALC,ALC06,AGEADJPREV,SEX,SEXM,21,26,5

In [58]:
data_inner.to_csv('State_Unique_Data.csv', header=True, index=False, encoding="utf-8")

In [59]:
print(data_inner.dtypes)

YearEnd                              int64
LocationAbbr                        object
State                               object
DataSource                          object
Topic                               object
Question                            object
DataValueUnit                       object
DataValueType                       object
DataValue                          float64
DataValueAlt                       float64
LowConfidenceLimit                 float64
HighConfidenceLimit                float64
StratificationCategory1             object
Stratification1                     object
LocationID                           int64
TopicID                             object
QuestionID                          object
DataValueTypeID                     object
StratificationCategoryID1           object
StratificationID1                   object
Overall Public School Rank 2022     object
Higher Ed Quality 2022              object
School Safety Rank 2022             object
dtype: object